### ISSUE TITLE
Does not issue warning for non-integer values

### ISSUE THREAD

**Issue by matthewwalk** [ryang-123/EECS2311-Project#2]
Version - Midterm Release
Component - Configurator
Platform - Surface Pro 5, Windows 10
Java Version - 8, Update 191 (64-Bit)

When entering the number of buttons in the "Talk Box Configuration App Wizard", any value may be entered into the text field.

The Configurator app does not continue or throw an error when a non-integer value in input between [1, 100]; however, the app should notify the user of invalid inputs via dialogue box or labels.

![Capture](https://user-images.githubusercontent.com/22501970/54139841-cd7d4480-43f8-11e9-8a37-55ab2ecec3f7.PNG)

**Comment by Nina1234y** [comment]
Added an error message
