### ISSUE TITLE
IDE crashes when you stop recording audio on Second Button

### ISSUE THREAD

**Issue by skilzer00** [ryang-123/EECS2311-Project#3]
Version - Midterm Release
Component - Simulator
Platform - Macbook Air 2015
Java Version - 
Eclipse Java EE IDE for Web Developers.
Version: 4.7.3.20180405-1200
Build id: 20180405-1200

![Screen Shot 2019-03-11 at 12 31 41 PM](https://user-images.githubusercontent.com/46536533/54140382-e2a6a300-43f9-11e9-9ee0-dcbe420eaedb.png)
Running the configurator app to display more than 2 buttons the audio recording function throws an Exception in thread "AWT-EventQueue-0".

**Comment by Nina1234y** [comment]
Solved the problem

**Comment by Nina1234y** [comment]
Solved the problem
